
export const PERSONAL_DETAILS = "PERSONAL_DETAILS"
export const EDUCATION_DETAILS = "EDUCATION_DETAILS"
export const PROJECT_DETAILS = "PROJECT_DETAILS"
export const TRAINING_DETAILS = "TRAINING_DETAILS"